# Generated by Django 4.2 on 2025-12-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClothesColor",
            fields=[
                (
                    "color",
                    models.CharField(
                        db_column="color",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rgb_tuple",
                    models.CharField(
                        blank=True, db_column="rgb_tuple", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "clothes_color",
            },
        ),
        migrations.CreateModel(
            name="Dress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="식별자", primary_key=True, serialize=False
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, db_column="스타일", max_length=100, null=True
                    ),
                ),
                (
                    "sub_style",
                    models.CharField(
                        blank=True, db_column="서브스타일", max_length=100, null=True
                    ),
                ),
                (
                    "dress_length",
                    models.CharField(
                        blank=True, db_column="원피스_기장", max_length=100, null=True
                    ),
                ),
                (
                    "dress_sleeve_length",
                    models.CharField(
                        blank=True,
                        db_column="원피스_소매기장",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "dress_material",
                    models.CharField(
                        blank=True, db_column="원피스_소재", max_length=100, null=True
                    ),
                ),
                (
                    "dress_print",
                    models.CharField(
                        blank=True, db_column="원피스_프린트", max_length=100, null=True
                    ),
                ),
                (
                    "dress_neckline",
                    models.CharField(
                        blank=True, db_column="원피스_넥라인", max_length=100, null=True
                    ),
                ),
                (
                    "dress_fit",
                    models.CharField(
                        blank=True, db_column="원피스_핏", max_length=100, null=True
                    ),
                ),
                (
                    "dress_detail",
                    models.CharField(
                        blank=True, db_column="원피스_디테일", max_length=255, null=True
                    ),
                ),
                (
                    "dress_color",
                    models.ForeignKey(
                        blank=True,
                        db_column="원피스_색상",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dress_set",
                        to="ui.clothescolor",
                    ),
                ),
            ],
            options={
                "db_table": "원피스",
            },
        ),
        migrations.CreateModel(
            name="Perfume",
            fields=[
                (
                    "perfume_id",
                    models.IntegerField(
                        db_column="perfume_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, db_column="url", max_length=500, null=True
                    ),
                ),
                ("perfume_name", models.CharField(db_column="Perfume", max_length=100)),
                ("brand", models.CharField(db_column="Brand", max_length=50)),
                (
                    "country",
                    models.CharField(
                        blank=True, db_column="Country", max_length=50, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_column="Gender", max_length=20, null=True
                    ),
                ),
                (
                    "rating_value",
                    models.FloatField(db_column="RatingValue", default=0.0),
                ),
                (
                    "rating_count",
                    models.IntegerField(db_column="RatingCount", default=0),
                ),
                ("year", models.IntegerField(blank=True, db_column="Year", null=True)),
                ("top", models.TextField(blank=True, db_column="Top", null=True)),
                ("middle", models.TextField(blank=True, db_column="Middle", null=True)),
                ("base", models.TextField(blank=True, db_column="Base", null=True)),
            ],
            options={
                "db_table": "perfume",
            },
        ),
        migrations.CreateModel(
            name="PerfumeColor",
            fields=[
                (
                    "mainaccord",
                    models.CharField(
                        db_column="mainaccord",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="color", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "perfume_color",
            },
        ),
        migrations.CreateModel(
            name="TopBottom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="식별자", primary_key=True, serialize=False
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, db_column="스타일", max_length=100, null=True
                    ),
                ),
                (
                    "sub_style",
                    models.CharField(
                        blank=True, db_column="서브스타일", max_length=100, null=True
                    ),
                ),
                (
                    "top_category",
                    models.CharField(
                        blank=True, db_column="상의_카테고리", max_length=100, null=True
                    ),
                ),
                (
                    "top_sleeve_length",
                    models.CharField(
                        blank=True, db_column="상의_소매기장", max_length=100, null=True
                    ),
                ),
                (
                    "top_material",
                    models.CharField(
                        blank=True, db_column="상의_소재", max_length=100, null=True
                    ),
                ),
                (
                    "top_print",
                    models.CharField(
                        blank=True, db_column="상의_프린트", max_length=100, null=True
                    ),
                ),
                (
                    "top_neckline",
                    models.CharField(
                        blank=True, db_column="상의_넥라인", max_length=100, null=True
                    ),
                ),
                (
                    "top_fit",
                    models.CharField(
                        blank=True, db_column="상의_핏", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_length",
                    models.CharField(
                        blank=True, db_column="하의_기장", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_category",
                    models.CharField(
                        blank=True, db_column="하의_카테고리", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_material",
                    models.CharField(
                        blank=True, db_column="하의_소재", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_fit",
                    models.CharField(
                        blank=True, db_column="하의_핏", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_color",
                    models.ForeignKey(
                        blank=True,
                        db_column="하의_색상",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bottom_set",
                        to="ui.clothescolor",
                    ),
                ),
                (
                    "top_color",
                    models.ForeignKey(
                        blank=True,
                        db_column="상의_색상",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="top_set",
                        to="ui.clothescolor",
                    ),
                ),
            ],
            options={
                "db_table": "상의_하의",
            },
        ),
        migrations.CreateModel(
            name="PerfumeClassification",
            fields=[
                (
                    "perfume",
                    models.OneToOneField(
                        db_column="perfume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="classification",
                        serialize=False,
                        to="ui.perfume",
                    ),
                ),
                (
                    "fragrance",
                    models.CharField(
                        blank=True, db_column="fragrance", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "perfume_classification",
            },
        ),
        migrations.CreateModel(
            name="PerfumeSeason",
            fields=[
                (
                    "perfume",
                    models.OneToOneField(
                        db_column="perfume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="season",
                        serialize=False,
                        to="ui.perfume",
                    ),
                ),
                ("spring", models.FloatField(db_column="spring", default=0.0)),
                ("summer", models.FloatField(db_column="summer", default=0.0)),
                ("fall", models.FloatField(db_column="fall", default=0.0)),
                ("winter", models.FloatField(db_column="winter", default=0.0)),
            ],
            options={
                "db_table": "perfume_season",
            },
        ),
        migrations.CreateModel(
            name="UserSmellingInput",
            fields=[
                (
                    "rate_id",
                    models.AutoField(
                        db_column="rate_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "smelling_user_id",
                    models.IntegerField(
                        blank=True, db_column="smelling_user_id", null=True
                    ),
                ),
                (
                    "top_color",
                    models.CharField(
                        blank=True, db_column="상의_색상", max_length=100, null=True
                    ),
                ),
                (
                    "top_category",
                    models.CharField(
                        blank=True, db_column="상의_카테고리", max_length=100, null=True
                    ),
                ),
                (
                    "top_img",
                    models.CharField(
                        blank=True,
                        db_column="상의_이미지_경로",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "bottom_color",
                    models.CharField(
                        blank=True, db_column="하의_색상", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_category",
                    models.CharField(
                        blank=True, db_column="하의_카테고리", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_img",
                    models.CharField(
                        blank=True,
                        db_column="하의_이미지_경로",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "dress_color",
                    models.CharField(
                        blank=True, db_column="원피스_색상", max_length=100, null=True
                    ),
                ),
                (
                    "dress_img",
                    models.CharField(
                        blank=True,
                        db_column="원피스_이미지_경로",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True, db_column="계절", max_length=50, null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_column="Brand", max_length=100, null=True
                    ),
                ),
                (
                    "perfume_img_url",
                    models.CharField(
                        blank=True,
                        db_column="perfume_img_url",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "smelling_rate",
                    models.IntegerField(
                        blank=True, db_column="smelling_rate", null=True
                    ),
                ),
                (
                    "bottom_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="하의_식별자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smelling_user_bottoms",
                        to="ui.topbottom",
                    ),
                ),
                (
                    "dress_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="원피스_식별자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smelling_user_dresses",
                        to="ui.dress",
                    ),
                ),
                (
                    "perfume_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="perfume_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smelling_user_perfume",
                        to="ui.perfume",
                    ),
                ),
                (
                    "top_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="상의_식별자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smelling_user_tops",
                        to="ui.topbottom",
                    ),
                ),
            ],
            options={
                "db_table": "user_smelling_input",
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="사용자_식별자", primary_key=True, serialize=False
                    ),
                ),
                (
                    "top_color",
                    models.CharField(
                        blank=True, db_column="상의_색상", max_length=100, null=True
                    ),
                ),
                (
                    "top_category",
                    models.CharField(
                        blank=True, db_column="상의_카테고리", max_length=100, null=True
                    ),
                ),
                (
                    "top_img",
                    models.CharField(
                        blank=True,
                        db_column="상의_이미지_경로",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "bottom_color",
                    models.CharField(
                        blank=True, db_column="하의_색상", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_category",
                    models.CharField(
                        blank=True, db_column="하의_카테고리", max_length=100, null=True
                    ),
                ),
                (
                    "bottom_img",
                    models.CharField(
                        blank=True,
                        db_column="하의_이미지_경로",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "dress_color",
                    models.CharField(
                        blank=True, db_column="원피스_색상", max_length=100, null=True
                    ),
                ),
                (
                    "dress_img",
                    models.CharField(
                        blank=True,
                        db_column="원피스_이미지_경로",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True, db_column="계절", max_length=50, null=True
                    ),
                ),
                (
                    "disliked_accord",
                    models.CharField(
                        blank=True, db_column="비선호_향조", max_length=50, null=True
                    ),
                ),
                (
                    "bottom_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="하의_식별자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_bottoms",
                        to="ui.topbottom",
                    ),
                ),
                (
                    "dress_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="원피스_식별자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_dresses",
                        to="ui.dress",
                    ),
                ),
                (
                    "top_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="상의_식별자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_tops",
                        to="ui.topbottom",
                    ),
                ),
            ],
            options={
                "db_table": "user_info",
            },
        ),
        migrations.CreateModel(
            name="PerfumeFeedback",
            fields=[
                (
                    "feedback_id",
                    models.AutoField(
                        db_column="feedback_id", primary_key=True, serialize=False
                    ),
                ),
                ("rating", models.IntegerField(db_column="rating")),
                (
                    "selected_tags",
                    models.CharField(
                        blank=True, db_column="selected_tags", max_length=255, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "perfume",
                    models.ForeignKey(
                        db_column="perfume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ui.perfume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ui.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "perfume_feedback",
            },
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord1",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord1",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord1",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord2",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord2",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord2",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord3",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord3",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord3",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord4",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord4",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord4",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord5",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord5",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord5",
                to="ui.perfumecolor",
            ),
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "season_score",
                    models.FloatField(blank=True, db_column="season_score", null=True),
                ),
                (
                    "color_score",
                    models.FloatField(blank=True, db_column="color_score", null=True),
                ),
                (
                    "style_score",
                    models.FloatField(blank=True, db_column="style_score", null=True),
                ),
                (
                    "myscore",
                    models.FloatField(blank=True, db_column="myscore", null=True),
                ),
                (
                    "user_style",
                    models.CharField(
                        blank=True, db_column="user_style", max_length=50, null=True
                    ),
                ),
                (
                    "perfume",
                    models.ForeignKey(
                        db_column="perfume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="ui.perfume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="ui.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "score",
                "unique_together": {("user", "perfume")},
            },
        ),
    ]
